export interface heroStats {
    id: number,
    name: string,
    localized_name: string,
    primary_attr: string,
    attack_type: string,
    roles: [
        string
    ],
    img: string,
    icon: string,
    base_health: number,
    base_health_regen: number,
    base_mana: number,
    base_mana_regen: number,
    base_armor: number,
    base_mr: number,
    base_attack_min: number,
    base_attack_max: number,
    base_str: number,
    base_agi: number,
    base_int: number,
    str_gain: number,
    agi_gain: number,
    int_gain: number,
    attack_range: number,
    projectile_speed: number,
    attack_rate: number,
    base_attack_time: number,
    attack_point: number,
    move_speed: number,
    turn_rate: number | null,
    cm_enabled: boolean,
    legs: number,
    day_vision: number,
    night_vision: number,
    hero_id: number,
    turbo_picks: number,
    turbo_wins: number,
    pro_ban: number,
    pro_win: number,
    pro_pick: number,
    // 1_pick: 3396,
    // 1_win: 1693,
    // 2_pick: 24720,
    // 2_win: 12430,
    // 3_pick: 58316,
    // 3_win: 29149,
    // 4_pick: 61902,
    // 4_win: 30533,
    // 5_pick: 35338,
    // 5_win: 17292,
    // 6_pick: 15148,
    // 6_win: 7414,
    // 7_pick: 6654,
    // 7_win: 3172,
    // 8_pick: 2545,
    // 8_win: 1161,
    // null_pick: 2069735,
    //     null_win: 0
}